import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Seeding database...")

  // ── Products ───────────────────────────────────────────────────────────────
  // Migrated directly from apps/frontend/kblt-frontgate/app/data/products.ts
  // isFeatured: true → Charizard, Blastoise, Venusaur, Blue-Eyes, Black Lotus
  // These replace the hardcoded featuredCards.ts on the frontend in V2

  await prisma.product.createMany({
    skipDuplicates: true,
    data: [
        {
    id: "1",
    name: "Bulbasaur",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Common",
    condition: "NM",
    price: 4.97,
    imageUrl: "/resources/bulbasaur_baseset_shadowless.jpg",
    stock: 3,
  },
  {
    id: "2",
    name: "Ivysaur",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Uncommon",
    condition: "LP",
    price: 2.97,
    imageUrl: "/resources/ivysaur_baseset_shadowless.jpg",
    stock: 5,
  },
  {
    id: "3",
    name: "Venusaur",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Holo Rare",
    condition: "NM",
    price: 655.98,
    imageUrl: "/resources/venusaur_baseset_shadowless.jpg",
    stock: 1,
  },
  {
    id: "4",
    name: "Squirtle",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Common",
    condition: "NM",
    price: 6.4,
    imageUrl: "/resources/squirtle_baseset_shadowless.jpg",
    stock: 4,
  },
  {
    id: "5",
    name: "Wartortle",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Uncommon",
    condition: "MP",
    price: 4.97,
    imageUrl: "/resources/wartortle_baseset_shadowless.jpg",
    stock: 2,
  },
  {
    id: "6",
    name: "Blastoise",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Holo Rare",
    condition: "NM",
    price: 877.18,
    imageUrl: "/resources/blastoise_baseset_shadowless.jpg",
    stock: 1,
  },
  {
    id: "7",
    name: "Charmander",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Common",
    condition: "NM",
    price: 38.0,
    imageUrl: "/resources/charmander_baseset_shadowless.jpg",
    stock: 2,
  },
  {
    id: "8",
    name: "Charmeleon",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Uncommon",
    condition: "LP",
    price: 22.4,
    imageUrl: "/resources/charmeleon_baseset_shadowless.jpg",
    stock: 3,
  },
  {
    id: "9",
    name: "Charizard",
    game: "Pokemon",
    set: "Base Set (Shadowless)",
    rarity: "Holo Rare",
    condition: "NM",
    price: 4520.5,
    imageUrl: "/resources/charizard_baseset_shadowless.jpg",
    stock: 1,
  },
  {
    id: "10",
    name: "Dark Charizard",
    game: "Pokemon",
    set: "Team Rocket",
    rarity: "Holo Rare",
    condition: "LP",
    price: 185.0,
    imageUrl: "/resources/darkcharizard_teamrocket_holo.jpg",
    stock: 2,
  },
  {
    id: "11",
    name: "Pikachu",
    game: "Pokemon",
    set: "Southern Islands Promo",
    rarity: "Ultra Rare",
    condition: "NM",
    price: 320.0,
    imageUrl: "/resources/pikachu_sp-promo.jpg",
    stock: 1,
  },

  // ─── Yu-Gi-Oh! ────────────────────────────────────────────────────────────
  {
    id: "12",
    name: "Blue-Eyes White Dragon",
    game: "YuGiOh",
    set: "Legend of Blue Eyes White Dragon",
    rarity: "Ultra Rare",
    condition: "NM",
    price: 340.0,
    imageUrl: "/resources/blueeyeswhitedragon_vg-promos.jpg",
    stock: 2,
  },
  {
    id: "13",
    name: "Dark Magician Girl",
    game: "YuGiOh",
    set: "Magician's Force",
    rarity: "Ultra Rare",
    condition: "LP",
    price: 3080.0,
    imageUrl: "/resources/dark_magician_girl_magiciansforce.jpg",
    stock: 3,
  },
  {
    id: "14",
    name: "Dark Magician",
    game: "YuGiOh",
    set: "Shonen Jump Magazine Promo",
    rarity: "Rare",
    condition: "NM",
    price: 99.00,
    imageUrl: "/resources/dark_magician_magazinepromos.jpg",
    stock: 4,
  },
  {
    id: "15",
    name: "Exodia the Forbidden One",
    game: "YuGiOh",
    set: "",
    rarity: "Ultra Rare",
    condition: "HP",
    price: 400.0,
    imageUrl: "/resources/exodia_forbidden_gxubpack.jpg",
    stock: 1,
  },
  {
    id: "16",
    name: "Red-Eyes B. Dragon",
    game: "YuGiOh",
    set: "Anniversary Pack",
    rarity: "Rare",
    condition: "LP",
    price: 52.99,
    imageUrl: "/resources/redeyesbdragon_annipack.jpg",
    stock: 5,
  },
  {
    id: "17",
    name: "Summoned Skull",
    game: "YuGiOh",
    set: "Metal Raiders",
    rarity: "Common",
    condition: "NM",
    price: 325.0,
    imageUrl: "/resources/summoned_skull_mr.jpg",
    stock: 6,
  },
  {
    id: "18",
    name: "Pot of Greed",
    game: "YuGiOh",
    set: "Tournament Pack 3",
    rarity: "Uncommon",
    condition: "MP",
    price: 22.0,
    imageUrl: "/resources/pot_greed_tp3.jpg",
    stock: 2,
  },

  // ─── Magic: The Gathering ──────────────────────────────────────────────────
  {
    id: "19",
    name: "Black Lotus",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Ultra Rare",
    condition: "HP",
    price: 28000.0,
    imageUrl: "/resources/blacklotus_beta.jpg",
    stock: 1,
  },
  {
    id: "20",
    name: "Black Lotus",
    game: "Magic",
    set: "Alpha Edition",
    rarity: "Ultra Rare",
    condition: "MP",
    price: 45000.0,
    imageUrl: "/resources/blacklotus_alpha.jpg",
    stock: 1,
  },
  {
    id: "21",
    name: "Ancestral Recall",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Ultra Rare",
    condition: "LP",
    price: 30952.75,
    imageUrl: "/resources/ancestral_recall_beta.jpg",
    stock: 1,
  },
  {
    id: "22",
    name: "Time Walk",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Ultra Rare",
    condition: "NM",
    price: 3200.0,
    imageUrl: "/resources/timewalk_beta.jpg",
    stock: 1,
  },
  {
    id: "23",
    name: "Mox Sapphire",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Ultra Rare",
    condition: "LP",
    price: 2100.0,
    imageUrl: "/resources/mox_sapphire_beta.jpg",
    stock: 2,
  },
  {
    id: "24",
    name: "Lightning Bolt",
    game: "Magic",
    set: "Alpha Edition",
    rarity: "Common",
    condition: "NM",
    price: 382.50,
    imageUrl: "/resources/lightning_bolt_alpha.jpg",
    stock: 3,
  },
  {
    id: "25",
    name: "Serra Angel",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Uncommon",
    condition: "NM",
    price: 353.71,
    imageUrl: "/resources/serra_angel_beta.jpg",
    stock: 4,
  },
  {
    id: "26",
    name: "Shivan Dragon",
    game: "Magic",
    set: "Beta Edition",
    rarity: "Rare",
    condition: "LP",
    price: 140.0,
    imageUrl: "/resources/shivan_dragon_beta.jpg",
    stock: 2,
  },
    ],
  })

  const count = await prisma.product.count()
  console.log(`✅ Seeded ${count} products`)
  console.log("🎉 Database ready")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })